name = "studycloud-worker"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# ==============================================================================
# Domaine Personnalisé Cloudflare
# ==============================================================================
routes = [
  { pattern = "api-worker.dkd-technologies.com", custom_domain = true }
]

# ==============================================================================
# Liaison Base de Données Cloudflare D1
# ==============================================================================
[[d1_databases]]
binding = "MON_D1_STUDYCLOUD"
database_name = "d1-studycloud"
database_id = "d1-studycloud" # Remplacez par votre database_id si nécessaire

# ==============================================================================
# Liaison Bucket de Stockage Cloudflare R2
# ==============================================================================
[[r2_buckets]]
binding = "MON_R2_STUDYCLOUD"
bucket_name = "r2-studycloud"
